### ISSUE TITLE
Update to marko v4

### ISSUE THREAD

**Issue by dillonbheadley** [poislagarde/gulp-marko-compile#2]
Marko has been updated quite a bit. Would be nice to have the latest!

**Comment by poislagarde** [comment]
Hey @insanetisane. Marko has grown a lot since I first published this gulp plugin, and now they support both run time compilation (via a require extension) and build time compilation (via a CLI).

See here for more info: http://markojs.com/docs/installing/#on-the-server

There's no point in using this plugin anymore. If you want to pre compile your marko files in a gulp build, you could just install `marko-cli` as a dev dependency and do this (with gulp 4):

```javascript
const { spawn } = require('child_process')
gulp.task('marko', () => spawn('marko', ['compile', 'hello.marko'], { stdio: 'inherit' }))
```

I'll update the readme for others to see.
